apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  healthMapping.json: |
{{ .Files.Get "static/mappings/healthMapping.json" | printf "%s" | indent 4 }}
  readyMapping.json: |
{{ .Files.Get "static/mappings/readyMapping.json" | printf "%s" | indent 4 }}
  breakMapping.json: |
{{ .Files.Get "static/mappings/breakMapping.json" | printf "%s" | indent 4 }}
  helloMapping.json: |
{{ .Files.Get "static/mappings/helloMapping.json" | printf "%s" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-files
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  hello.json: |
{{ .Files.Get "static/responses/hello.json" | printf "%s" | indent 4 }}