apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.name_version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: serviceport
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: serviceport
  selector:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
