replicaCount: 1

app:
  logLevel: "INFO"
  serverPort: "8080"
  mountedConfigMapName: "wiremock"
  mountedFilesConfigMapName: "wiremock-files"
  readOnlyRootFilesystem: false


image:
  snapshot: false
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: NodePort
  port: 8080
  nodePort: ""

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - wiremock.local

podAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
